// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jwlmqpjtesjwvujsquiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp3bG1xcGp0ZXNqd3Z1anNxdWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5MjcyNTksImV4cCI6MjA5NDUwMzI1OX0.sbw5QOUGd3OiRyXDmpDqwhqIB66u3dmvNvkYnSN9yog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});